# POSTEST4 PREPROCESSING
### LIDYA SIMANUNGKALIT
### 2009106125
### KB C1 20


#### IMPORT LIBRARY

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("cars.csv")
data.head()

,manufacturer_name,model_name,transmission,color,odometer_value,year_produced,engine_fuel,engine_has_gas,engine_type,engine_capacity,...,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,duration_listed
0,Subaru,Outback,automatic,silver,190000,2010,gasoline,False,gasoline,2.5,...,True,True,True,False,True,False,True,True,True,16
1,Subaru,Outback,automatic,blue,290000,2002,gasoline,False,gasoline,3.0,...,True,False,False,True,True,False,False,False,True,83
2,Subaru,Forester,automatic,red,402000,2001,gasoline,False,gasoline,2.5,...,True,False,False,False,False,False,False,True,True,151
3,Subaru,Impreza,mechanical,blue,10000,1999,gasoline,False,gasoline,3.0,...,False,False,False,False,False,False,False,False,False,86
4,Subaru,Legacy,automatic,black,280000,2001,gasoline,False,gasoline,2.5,...,True,False,True,True,False,False,False,False,True,7

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38531 entries, 0 to 38530
Data columns (total 30 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   manufacturer_name  38531 non-null  object
 1   model_name         38531 non-null  object
 2   transmission       38531 non-null  object
 3   color              38531 non-null  object
 4   odometer_value     38531 non-null  int64
 5   year_produced      38531 non-null  int64
 6   engine_fuel        38531 non-null  object
 7   engine_has_gas     38531 non-null  bool
 8   engine_type        38531 non-null  object
 9   engine_capacity    38521 non-null  float64
 10  body_type          38531 non-null  object
 11  has_warranty       38531 non-null  bool
 12  state              38531 non-null  object
 13  drivetrain         38531 non-null  object
 14  price_usd          38531 non-null  float64
 15  is_exchangeable    38531 non-null  bool
 16  location_region    38531 non-null  object
 17  number_of_photos   38531 non-null  int64
 18  up_counter         38531 non-null  int64
 19  feature_0          38531 non-null  bool
 20  feature_1          38531 non-null  bool
 21  feature_2          38531 non-null  bool
 22  feature_3          38531 non-null  bool
 23  feature_4          38531 non-null  bool
 24  feature_5          38531 non-null  bool
 25  feature_6          38531 non-null  bool
 26  feature_7          38531 non-null  bool
 27  feature_8          38531 non-null  bool
 28  feature_9          38531 non-null  bool
 29  duration_listed    38531 non-null  int64
dtypes: bool(13), float64(2), int64(5), object(10)
memory usage: 5.5+ MB

In [4]:
data.shape

(38531, 30)

# DATA SPLIT

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X = data.iloc[:,:-1] #mengambil semua elemen dataset tanpa terkecuali -1
y = data.iloc[:,-1]

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3)

In [8]:
print("dimensi X_train : ",X_train.shape)
print("dimensi X_test : ",X_test.shape)
print("dimensi y_train : ",y_train.shape)
print("dimensi y_test : ",y_test.shape)

dimensi X_train :  (26971, 29)
dimensi X_test :  (11560, 29)
dimensi y_train :  (26971,)
dimensi y_test :  (11560,)

# DATA CLEANING

### Menangani nilai null

In [9]:
#cek data null
data.isna().sum()

manufacturer_name     0
model_name            0
transmission          0
color                 0
odometer_value        0
year_produced         0
engine_fuel           0
engine_has_gas        0
engine_type           0
engine_capacity      10
body_type             0
has_warranty          0
state                 0
drivetrain            0
price_usd             0
is_exchangeable       0
location_region       0
number_of_photos      0
up_counter            0
feature_0             0
feature_1             0
feature_2             0
feature_3             0
feature_4             0
feature_5             0
feature_6             0
feature_7             0
feature_8             0
feature_9             0
duration_listed       0
dtype: int64

In [10]:
from sklearn.impute import SimpleImputer

In [11]:
imputer_float = SimpleImputer(strategy="mean")

In [12]:
data['engine_capacity'] = imputer_float.fit_transform(data[["engine_capacity"]])

In [13]:
data.isna().sum()

manufacturer_name    0
model_name           0
transmission         0
color                0
odometer_value       0
year_produced        0
engine_fuel          0
engine_has_gas       0
engine_type          0
engine_capacity      0
body_type            0
has_warranty         0
state                0
drivetrain           0
price_usd            0
is_exchangeable      0
location_region      0
number_of_photos     0
up_counter           0
feature_0            0
feature_1            0
feature_2            0
feature_3            0
feature_4            0
feature_5            0
feature_6            0
feature_7            0
feature_8            0
feature_9            0
duration_listed      0
dtype: int64

# Menangani Data Duplicate

In [14]:
data.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
38526    False
38527    False
38528    False
38529    False
38530    False
Length: 38531, dtype: bool

In [15]:
data.duplicated().sum()

40

In [16]:
data[data.duplicated()]

,manufacturer_name,model_name,transmission,color,odometer_value,year_produced,engine_fuel,engine_has_gas,engine_type,engine_capacity,...,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,duration_listed
5767,Mitsubishi,Lancer,automatic,black,250000,2003,gasoline,False,gasoline,2.0,...,True,False,False,False,False,False,False,False,False,50
6556,Citroen,Xantia,mechanical,silver,520000,1998,diesel,False,diesel,2.1,...,True,False,False,False,False,False,False,False,False,16
9996,Ford,Scorpio,mechanical,yellow,55555,1995,gasoline,False,gasoline,2.0,...,False,False,False,False,False,False,False,False,False,1
11380,Ford,Transit,mechanical,grey,700000,2005,diesel,False,diesel,2.4,...,False,False,False,False,False,False,False,False,False,60
11704,Ford,Mondeo,mechanical,green,380000,1998,diesel,False,diesel,1.8,...,False,False,False,False,True,False,False,True,True,67
12810,Renault,19,mechanical,blue,99999,1992,gasoline,False,gasoline,1.7,...,False,False,False,False,False,False,False,False,False,3
17338,Volkswagen,Touareg,automatic,grey,337400,2008,diesel,False,diesel,2.5,...,True,True,False,False,True,False,False,True,True,11
18184,Volkswagen,Passat,mechanical,black,157000,2008,gasoline,False,gasoline,1.8,...,True,True,True,True,True,False,True,True,True,42
31993,Skoda,Rapid,automatic,silver,0,2019,gasoline,False,gasoline,1.6,...,False,False,False,False,False,False,False,False,False,3
32017,Skoda,Rapid,mechanical,blue,0,2019,gasoline,False,gasoline,1.6,...,False,False,False,False,False,False,False,False,False,3
32018,Skoda,Rapid,mechanical,blue,0,2019,gasoline,False,gasoline,1.6,...,False,False,False,False,False,False,False,False,False,3
32022,Skoda,Rapid,mechanical,black,0,2019,gasoline,False,gasoline,1.6,...,False,False,False,False,False,False,False,False,False,3
32025,Skoda,Rapid,mechanical,brown,0,2019,gasoline,False,gasoline,1.6,...,False,False,False,False,False,False,False,False,False,3
32028,Skoda,Rapid,mechanical,white,0,2019,gasoline,False,gasoline,1.6,...,False,False,False,False,False,False,False,False,False,3
32034,Skoda,Rapid,automatic,silver,0,2019,gasoline,False,gasoline,1.6,...,False,False,False,False,False,False,False,False,False,3
32036,Skoda,Rapid,automatic,other,0,2019,gasoline,False,gasoline,1.6,...,False,False,False,False,False,False,False,False,False,3
32053,Skoda,Rapid,mechanical,blue,0,2019,gasoline,False,gasoline,1.6,...,False,False,False,False,False,False,False,False,False,3
32126,Skoda,Octavia,mechanical,white,0,2019,gasoline,False,gasoline,1.4,...,False,False,False,False,False,False,False,False,False,26
32128,Skoda,Kodiaq,automatic,silver,0,2019,gasoline,False,gasoline,2.0,...,False,False,False,False,False,False,False,False,False,26
32179,Skoda,Rapid,mechanical,green,0,2019,gasoline,False,gasoline,1.6,...,False,False,False,False,False,False,False,False,False,26
32180,Skoda,Rapid,mechanical,green,0,2019,gasoline,False,gasoline,1.6,...,False,False,False,False,False,False,False,False,False,26
32295,Skoda,Rapid,mechanical,blue,0,2019,gasoline,False,gasoline,1.6,...,False,False,False,False,False,False,False,False,False,2
32296,Skoda,Rapid,mechanical,blue,0,2019,gasoline,False,gasoline,1.6,...,False,False,False,False,False,False,False,False,False,2
32298,Skoda,Rapid,mechanical,blue,0,2019,gasoline,False,gasoline,1.6,...,False,False,False,False,False,False,False,False,False,2
32299,Skoda,Rapid,mechanical,blue,0,2019,gasoline,False,gasoline,1.6,...,False,False,False,False,False,False,False,False,False,2
32301,Skoda,Rapid,mechanical,other,0,2019,gasoline,False,gasoline,1.6,...,False,False,False,False,False,False,False,False,False,2
32302,Skoda,Rapid,mechanical,other,0,2019,gasoline,False,gasoline,1.6,...,False,False,False,False,False,False,False,False,False,2
32304,Skoda,Rapid,mechanical,other,0,2019,gasoline,False,gasoline,1.6,...,False,False,False,False,False,False,False,False,False,2
32306,Skoda,Rapid,mechanical,black,0,2019,gasoline,False,gasoline,1.6,...,False,False,False,False,False,False,False,False,False,2
32307,Skoda,Rapid,mechanical,black,0,2019,gasoline,False,gasoline,1.6,...,False,False,False,False,False,False,False,False,False,2
32308,Skoda,Rapid,mechanical,black,0,2019,gasoline,False,gasoline,1.6,...,False,False,False,False,False,False,False,False,False,2
32310,Skoda,Rapid,mechanical,black,0,2019,gasoline,False,gasoline,1.6,...,False,False,False,False,False,False,False,False,False,2
32312,Skoda,Rapid,mechanical,brown,0,2019,gasoline,False,gasoline,1.6,...,False,False,False,False,False,False,False,False,False,2
32313,Skoda,Rapid,mechanical,brown,0,2019,gasoline,False,gasoline,1.6,...,False,False,False,False,False,False,False,False,False,2
32315,Skoda,Rapid,mechanical,brown,0,2019,gasoline,False,gasoline,1.6,...,False,False,False,False,False,False,False,False,False,2
32316,Skoda,Rapid,mechanical,brown,0,2019,gasoline,False,gasoline,1.6,...,False,False,False,False,False,False,False,False,False,2
32317,Skoda,Rapid,mechanical,brown,0,2019,gasoline,False,gasoline,1.6,...,False,False,False,False,False,False,False,False,False,2
32318,Skoda,Rapid,mechanical,brown,0,2019,gasoline,False,gasoline,1.6,...,False,False,False,False,False,False,False,False,False,2
32321,Skoda,Rapid,mechanical,silver,0,2019,gasoline,False,gasoline,1.6,...,False,False,False,False,False,False,False,False,False,2
32325,Skoda,Rapid,mechanical,white,0,2019,gasoline,False,gasoline,1.6,...,False,False,False,False,False,False,False,False,False,2

In [17]:
data.drop_duplicates(inplace=True)

In [18]:
data.duplicated().sum()

0

# mengubah tipe data

In [19]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 38491 entries, 0 to 38530
Data columns (total 30 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   manufacturer_name  38491 non-null  object
 1   model_name         38491 non-null  object
 2   transmission       38491 non-null  object
 3   color              38491 non-null  object
 4   odometer_value     38491 non-null  int64
 5   year_produced      38491 non-null  int64
 6   engine_fuel        38491 non-null  object
 7   engine_has_gas     38491 non-null  bool
 8   engine_type        38491 non-null  object
 9   engine_capacity    38491 non-null  float64
 10  body_type          38491 non-null  object
 11  has_warranty       38491 non-null  bool
 12  state              38491 non-null  object
 13  drivetrain         38491 non-null  object
 14  price_usd          38491 non-null  float64
 15  is_exchangeable    38491 non-null  bool
 16  location_region    38491 non-null  object
 17  number_of_photos   38491 non-null  int64
 18  up_counter         38491 non-null  int64
 19  feature_0          38491 non-null  bool
 20  feature_1          38491 non-null  bool
 21  feature_2          38491 non-null  bool
 22  feature_3          38491 non-null  bool
 23  feature_4          38491 non-null  bool
 24  feature_5          38491 non-null  bool
 25  feature_6          38491 non-null  bool
 26  feature_7          38491 non-null  bool
 27  feature_8          38491 non-null  bool
 28  feature_9          38491 non-null  bool
 29  duration_listed    38491 non-null  int64
dtypes: bool(13), float64(2), int64(5), object(10)
memory usage: 5.8+ MB

In [20]:
data["engine_capacity"].fillna(0, inplace=True)

In [21]:
data.isna().sum()

manufacturer_name    0
model_name           0
transmission         0
color                0
odometer_value       0
year_produced        0
engine_fuel          0
engine_has_gas       0
engine_type          0
engine_capacity      0
body_type            0
has_warranty         0
state                0
drivetrain           0
price_usd            0
is_exchangeable      0
location_region      0
number_of_photos     0
up_counter           0
feature_0            0
feature_1            0
feature_2            0
feature_3            0
feature_4            0
feature_5            0
feature_6            0
feature_7            0
feature_8            0
feature_9            0
duration_listed      0
dtype: int64

In [22]:
data['engine_capacity'] = data['engine_capacity'].astype(int)

In [23]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 38491 entries, 0 to 38530
Data columns (total 30 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   manufacturer_name  38491 non-null  object
 1   model_name         38491 non-null  object
 2   transmission       38491 non-null  object
 3   color              38491 non-null  object
 4   odometer_value     38491 non-null  int64
 5   year_produced      38491 non-null  int64
 6   engine_fuel        38491 non-null  object
 7   engine_has_gas     38491 non-null  bool
 8   engine_type        38491 non-null  object
 9   engine_capacity    38491 non-null  int32
 10  body_type          38491 non-null  object
 11  has_warranty       38491 non-null  bool
 12  state              38491 non-null  object
 13  drivetrain         38491 non-null  object
 14  price_usd          38491 non-null  float64
 15  is_exchangeable    38491 non-null  bool
 16  location_region    38491 non-null  object
 17  number_of_photos   38491 non-null  int64
 18  up_counter         38491 non-null  int64
 19  feature_0          38491 non-null  bool
 20  feature_1          38491 non-null  bool
 21  feature_2          38491 non-null  bool
 22  feature_3          38491 non-null  bool
 23  feature_4          38491 non-null  bool
 24  feature_5          38491 non-null  bool
 25  feature_6          38491 non-null  bool
 26  feature_7          38491 non-null  bool
 27  feature_8          38491 non-null  bool
 28  feature_9          38491 non-null  bool
 29  duration_listed    38491 non-null  int64
dtypes: bool(13), float64(1), int32(1), int64(5), object(10)
memory usage: 5.6+ MB

# DATA TRANSFORMING

##  STANDARISASI

In [24]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 38491 entries, 0 to 38530
Data columns (total 30 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   manufacturer_name  38491 non-null  object
 1   model_name         38491 non-null  object
 2   transmission       38491 non-null  object
 3   color              38491 non-null  object
 4   odometer_value     38491 non-null  int64
 5   year_produced      38491 non-null  int64
 6   engine_fuel        38491 non-null  object
 7   engine_has_gas     38491 non-null  bool
 8   engine_type        38491 non-null  object
 9   engine_capacity    38491 non-null  int32
 10  body_type          38491 non-null  object
 11  has_warranty       38491 non-null  bool
 12  state              38491 non-null  object
 13  drivetrain         38491 non-null  object
 14  price_usd          38491 non-null  float64
 15  is_exchangeable    38491 non-null  bool
 16  location_region    38491 non-null  object
 17  number_of_photos   38491 non-null  int64
 18  up_counter         38491 non-null  int64
 19  feature_0          38491 non-null  bool
 20  feature_1          38491 non-null  bool
 21  feature_2          38491 non-null  bool
 22  feature_3          38491 non-null  bool
 23  feature_4          38491 non-null  bool
 24  feature_5          38491 non-null  bool
 25  feature_6          38491 non-null  bool
 26  feature_7          38491 non-null  bool
 27  feature_8          38491 non-null  bool
 28  feature_9          38491 non-null  bool
 29  duration_listed    38491 non-null  int64
dtypes: bool(13), float64(1), int32(1), int64(5), object(10)
memory usage: 5.6+ MB

In [25]:
df_standarisasi= data.copy()
df_standarisasi.drop('manufacturer_name', axis =1,inplace= True)
df_standarisasi.drop('model_name', axis =1,inplace= True)
df_standarisasi.drop('transmission', axis =1,inplace= True)
df_standarisasi.drop('color', axis =1,inplace= True)
df_standarisasi.drop('engine_fuel', axis =1,inplace= True)
df_standarisasi.drop('body_type', axis =1,inplace= True)
df_standarisasi.drop('state', axis =1,inplace= True)
df_standarisasi.drop('drivetrain', axis =1,inplace= True)
df_standarisasi.drop('location_region', axis =1,inplace= True)
df_standarisasi.drop('engine_type' , axis =1,inplace= True)

In [26]:
from sklearn.preprocessing import StandardScaler

In [27]:
scaler = StandardScaler()
scale_data = scaler.fit_transform(df_standarisasi)
print("Nilai data sebelum standarisasi : ")
print(data[0:4])
print("Nilai standar deviasi : ", np.std(data))
print("Nilai data setelah standarisasi : ")
print(scale_data)
print("Nilai standar deviasi : ", np.std(scale_data))

Nilai data sebelum standarisasi :
  manufacturer_name model_name transmission   color  odometer_value  \
0            Subaru    Outback    automatic  silver          190000
1            Subaru    Outback    automatic    blue          290000
2            Subaru   Forester    automatic     red          402000
3            Subaru    Impreza   mechanical    blue           10000

   year_produced engine_fuel  engine_has_gas engine_type  engine_capacity  \
0           2010    gasoline           False    gasoline                2
1           2002    gasoline           False    gasoline                3
2           2001    gasoline           False    gasoline                2
3           1999    gasoline           False    gasoline                3

   ... feature_1  feature_2 feature_3 feature_4  feature_5  feature_6  \
0  ...      True       True      True     False       True      False
1  ...      True      False     False      True       True      False
2  ...      True      False     False     False      False      False
3  ...     False      False     False     False      False      False

  feature_7  feature_8  feature_9  duration_listed
0      True       True       True               16
1     False      False       True               83
2     False       True       True              151
3     False      False      False               86

[4 rows x 30 columns]
Nilai standar deviasi :  odometer_value      135916.561259
year_produced            8.056052
engine_has_gas           0.183768
engine_capacity          0.775479
has_warranty             0.103520
price_usd             6423.950292
is_exchangeable          0.477611
number_of_photos         6.093891
up_counter              43.306487
feature_0                0.419459
feature_1                0.488257
feature_2                0.416922
feature_3                0.447049
feature_4                0.428109
feature_5                0.478926
feature_6                0.376646
feature_7                0.440791
feature_8                0.492839
feature_9                0.493570
duration_listed        112.859777
dtype: float64
Nilai data setelah standarisasi :
[[-0.43451887  0.87749995 -0.1904318  ...  1.18561693  0.8510891
  -0.57283562]
 [ 0.30122664 -0.11554233 -0.1904318  ... -0.84344275  0.8510891
   0.02082141]
 [ 1.12526162 -0.23967261 -0.1904318  ...  1.18561693  0.8510891
   0.623339  ]
 ...
 [ 3.89134837 -0.3638029  -0.1904318  ...  1.18561693  0.8510891
   2.55493949]
 [-1.68528624 -0.23967261 -0.1904318  ... -0.84344275  0.8510891
   3.62706637]
 [ 0.35809241 -0.3638029  -0.1904318  ... -0.84344275  0.8510891
   4.88526485]]
Nilai standar deviasi :  0.9999999999999999

C:\Users\LENOVO\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\core\fromnumeric.py:3571: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  return std(axis=axis, dtype=dtype, out=out, ddof=ddof, **kwargs)

# NORMALISASI

In [28]:
dt_normalisasi = data.copy()
dt_normalisasi['odometer_value'] = (dt_normalisasi['odometer_value'] - dt_normalisasi['odometer_value'].min()) / (dt_normalisasi['odometer_value'].max() - dt_normalisasi['odometer_value'].min())
dt_normalisasi['year_produced']   = (dt_normalisasi['year_produced'] - dt_normalisasi['year_produced'].min()) / (dt_normalisasi['year_produced'].max() - dt_normalisasi['year_produced'].min())
print(dt_normalisasi['odometer_value'])
print(dt_normalisasi['year_produced'])

0        0.190000
1        0.290000
2        0.402000
3        0.010000
4        0.280000
           ...
38526    0.290000
38527    0.321000
38528    0.777957
38529    0.020000
38530    0.297729
Name: odometer_value, Length: 38491, dtype: float64
0        0.883117
1        0.779221
2        0.766234
3        0.740260
4        0.766234
           ...
38526    0.753247
38527    0.805195
38528    0.753247
38529    0.766234
38530    0.753247
Name: year_produced, Length: 38491, dtype: float64

# ONE HOT ENCODING

In [29]:
data.keys()

Index(['manufacturer_name', 'model_name', 'transmission', 'color',
       'odometer_value', 'year_produced', 'engine_fuel', 'engine_has_gas',
       'engine_type', 'engine_capacity', 'body_type', 'has_warranty', 'state',
       'drivetrain', 'price_usd', 'is_exchangeable', 'location_region',
       'number_of_photos', 'up_counter', 'feature_0', 'feature_1', 'feature_2',
       'feature_3', 'feature_4', 'feature_5', 'feature_6', 'feature_7',
       'feature_8', 'feature_9', 'duration_listed'],
      dtype='object')

In [30]:
from sklearn.preprocessing import OneHotEncoder

In [31]:
data.head()

,manufacturer_name,model_name,transmission,color,odometer_value,year_produced,engine_fuel,engine_has_gas,engine_type,engine_capacity,...,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,duration_listed
0,Subaru,Outback,automatic,silver,190000,2010,gasoline,False,gasoline,2,...,True,True,True,False,True,False,True,True,True,16
1,Subaru,Outback,automatic,blue,290000,2002,gasoline,False,gasoline,3,...,True,False,False,True,True,False,False,False,True,83
2,Subaru,Forester,automatic,red,402000,2001,gasoline,False,gasoline,2,...,True,False,False,False,False,False,False,True,True,151
3,Subaru,Impreza,mechanical,blue,10000,1999,gasoline,False,gasoline,3,...,False,False,False,False,False,False,False,False,False,86
4,Subaru,Legacy,automatic,black,280000,2001,gasoline,False,gasoline,2,...,True,False,True,True,False,False,False,False,True,7

In [32]:
encoder = OneHotEncoder(sparse=False)
tipe = encoder.fit_transform(data[["transmission"]])

tipes = pd.DataFrame(tipe)
data = data.join(tipes)
data.head()

,manufacturer_name,model_name,transmission,color,odometer_value,year_produced,engine_fuel,engine_has_gas,engine_type,engine_capacity,...,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,duration_listed,0,1
0,Subaru,Outback,automatic,silver,190000,2010,gasoline,False,gasoline,2,...,True,False,True,False,True,True,True,16,1.0,0.0
1,Subaru,Outback,automatic,blue,290000,2002,gasoline,False,gasoline,3,...,False,True,True,False,False,False,True,83,1.0,0.0
2,Subaru,Forester,automatic,red,402000,2001,gasoline,False,gasoline,2,...,False,False,False,False,False,True,True,151,1.0,0.0
3,Subaru,Impreza,mechanical,blue,10000,1999,gasoline,False,gasoline,3,...,False,False,False,False,False,False,False,86,0.0,1.0
4,Subaru,Legacy,automatic,black,280000,2001,gasoline,False,gasoline,2,...,True,True,False,False,False,False,True,7,1.0,0.0

In [33]:
data['transmission'].value_counts()

mechanical    25599
automatic     12892
Name: transmission, dtype: int64

In [34]:
data = data.rename(columns={
    0 : 'mechanical',
    1 : 'automatic',
   
})

data.head()

,manufacturer_name,model_name,transmission,color,odometer_value,year_produced,engine_fuel,engine_has_gas,engine_type,engine_capacity,...,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,duration_listed,mechanical,automatic
0,Subaru,Outback,automatic,silver,190000,2010,gasoline,False,gasoline,2,...,True,False,True,False,True,True,True,16,1.0,0.0
1,Subaru,Outback,automatic,blue,290000,2002,gasoline,False,gasoline,3,...,False,True,True,False,False,False,True,83,1.0,0.0
2,Subaru,Forester,automatic,red,402000,2001,gasoline,False,gasoline,2,...,False,False,False,False,False,True,True,151,1.0,0.0
3,Subaru,Impreza,mechanical,blue,10000,1999,gasoline,False,gasoline,3,...,False,False,False,False,False,False,False,86,0.0,1.0
4,Subaru,Legacy,automatic,black,280000,2001,gasoline,False,gasoline,2,...,True,True,False,False,False,False,True,7,1.0,0.0

In [35]:
data.keys()

Index(['manufacturer_name', 'model_name', 'transmission', 'color',
       'odometer_value', 'year_produced', 'engine_fuel', 'engine_has_gas',
       'engine_type', 'engine_capacity', 'body_type', 'has_warranty', 'state',
       'drivetrain', 'price_usd', 'is_exchangeable', 'location_region',
       'number_of_photos', 'up_counter', 'feature_0', 'feature_1', 'feature_2',
       'feature_3', 'feature_4', 'feature_5', 'feature_6', 'feature_7',
       'feature_8', 'feature_9', 'duration_listed', 'mechanical', 'automatic'],
      dtype='object')